#include "avcodec_utils.h"

static const enum AVCodecID codec_type_mapping[] = {
    AV_CODEC_ID_NONE,
    AV_CODEC_ID_AAC,
    AV_CODEC_ID_ALAC,
    AV_CODEC_ID_FLAC,
    AV_CODEC_ID_MP3,
    AV_CODEC_ID_OPUS,
    AV_CODEC_ID_AC3,
    AV_CODEC_ID_EAC3,
    AV_CODEC_ID_VORBIS,
    AV_CODEC_ID_MP2,
    AV_CODEC_ID_DTS,
    AV_CODEC_ID_DVAUDIO,
    AV_CODEC_ID_WMAV1,
    AV_CODEC_ID_WMAV2,
    AV_CODEC_ID_MACE3,
    AV_CODEC_ID_MACE6,
    AV_CODEC_ID_VMDAUDIO,
    AV_CODEC_ID_MP3ADU,
    AV_CODEC_ID_MP3ON4,
    AV_CODEC_ID_SHORTEN,
    AV_CODEC_ID_WESTWOOD_SND1,
    AV_CODEC_ID_GSM,
    AV_CODEC_ID_QDM2,
    AV_CODEC_ID_COOK,
    AV_CODEC_ID_TRUESPEECH,
    AV_CODEC_ID_TTA,
    AV_CODEC_ID_SMACKAUDIO,
    AV_CODEC_ID_QCELP,
    AV_CODEC_ID_WAVPACK,
    AV_CODEC_ID_DSICINAUDIO,
    AV_CODEC_ID_IMC,
    AV_CODEC_ID_MUSEPACK7,
    AV_CODEC_ID_MLP,
    AV_CODEC_ID_GSM_MS,
    AV_CODEC_ID_ATRAC3,
    AV_CODEC_ID_APE,
    AV_CODEC_ID_NELLYMOSER,
    AV_CODEC_ID_MUSEPACK8,
    AV_CODEC_ID_SPEEX,
    AV_CODEC_ID_WMAVOICE,
    AV_CODEC_ID_WMAPRO,
    AV_CODEC_ID_WMALOSSLESS,
    AV_CODEC_ID_ATRAC3P,
    AV_CODEC_ID_SIPR,
    AV_CODEC_ID_MP1,
    AV_CODEC_ID_TWINVQ,
    AV_CODEC_ID_TRUEHD,
    AV_CODEC_ID_MP4ALS,
    AV_CODEC_ID_ATRAC1,
    AV_CODEC_ID_BINKAUDIO_RDFT,
    AV_CODEC_ID_BINKAUDIO_DCT,
    AV_CODEC_ID_AAC_LATM,
    AV_CODEC_ID_QDMC,
    AV_CODEC_ID_CELT,
    AV_CODEC_ID_G723_1,
    AV_CODEC_ID_G729,
    AV_CODEC_ID_8SVX_EXP,
    AV_CODEC_ID_8SVX_FIB,
    AV_CODEC_ID_BMV_AUDIO,
    AV_CODEC_ID_RALF,
    AV_CODEC_ID_IAC,
    AV_CODEC_ID_ILBC,
    AV_CODEC_ID_COMFORT_NOISE,
    AV_CODEC_ID_TAK,
    AV_CODEC_ID_METASOUND,
    AV_CODEC_ID_PAF_AUDIO,
    AV_CODEC_ID_ON2AVC,
    AV_CODEC_ID_DSS_SP,
    AV_CODEC_ID_CODEC2,
    AV_CODEC_ID_FFWAVESYNTH,
    AV_CODEC_ID_SONIC,
    AV_CODEC_ID_SONIC_LS,
    AV_CODEC_ID_EVRC,
    AV_CODEC_ID_SMV,
    AV_CODEC_ID_DSD_LSBF,
    AV_CODEC_ID_DSD_MSBF,
    AV_CODEC_ID_DSD_LSBF_PLANAR,
    AV_CODEC_ID_DSD_MSBF_PLANAR,
    AV_CODEC_ID_4GV,
    AV_CODEC_ID_INTERPLAY_ACM,
    AV_CODEC_ID_XMA1,
    AV_CODEC_ID_XMA2,
    AV_CODEC_ID_DST,
    AV_CODEC_ID_ATRAC3AL,
    AV_CODEC_ID_ATRAC3PAL,
    AV_CODEC_ID_DOLBY_E,
    AV_CODEC_ID_APTX,
    AV_CODEC_ID_APTX_HD,
    AV_CODEC_ID_SBC,
    AV_CODEC_ID_ATRAC9,
    AV_CODEC_ID_HCOM,
    AV_CODEC_ID_ACELP_KELVIN,
    AV_CODEC_ID_MPEGH_3D_AUDIO,
    AV_CODEC_ID_SIREN,
    AV_CODEC_ID_HCA,
    AV_CODEC_ID_FASTAUDIO,
    AV_CODEC_ID_MSNSIREN,
    AV_CODEC_ID_DFPWM,
    AV_CODEC_ID_BONK,
    AV_CODEC_ID_MISC4,
    AV_CODEC_ID_APAC,
    AV_CODEC_ID_FTR,
    AV_CODEC_ID_WAVARC,
    AV_CODEC_ID_RKA,
    AV_CODEC_ID_PCM_S16LE,
    AV_CODEC_ID_PCM_S16BE,
    AV_CODEC_ID_PCM_U16LE,
    AV_CODEC_ID_PCM_U16BE,
    AV_CODEC_ID_PCM_S8,
    AV_CODEC_ID_PCM_U8,
    AV_CODEC_ID_PCM_MULAW,
    AV_CODEC_ID_PCM_ALAW,
    AV_CODEC_ID_PCM_S32LE,
    AV_CODEC_ID_PCM_S32BE,
    AV_CODEC_ID_PCM_U32LE,
    AV_CODEC_ID_PCM_U32BE,
    AV_CODEC_ID_PCM_S24LE,
    AV_CODEC_ID_PCM_S24BE,
    AV_CODEC_ID_PCM_U24LE,
    AV_CODEC_ID_PCM_U24BE,
    AV_CODEC_ID_PCM_S24DAUD,
    AV_CODEC_ID_PCM_ZORK,
    AV_CODEC_ID_PCM_S16LE_PLANAR,
    AV_CODEC_ID_PCM_DVD,
    AV_CODEC_ID_PCM_F32BE,
    AV_CODEC_ID_PCM_F32LE,
    AV_CODEC_ID_PCM_F64BE,
    AV_CODEC_ID_PCM_F64LE,
    AV_CODEC_ID_PCM_BLURAY,
    AV_CODEC_ID_PCM_LXF,
    AV_CODEC_ID_S302M,
    AV_CODEC_ID_PCM_S8_PLANAR,
    AV_CODEC_ID_PCM_S24LE_PLANAR,
    AV_CODEC_ID_PCM_S32LE_PLANAR,
    AV_CODEC_ID_PCM_S16BE_PLANAR,
    AV_CODEC_ID_PCM_S64LE,
    AV_CODEC_ID_PCM_S64BE,
    AV_CODEC_ID_PCM_F16LE,
    AV_CODEC_ID_PCM_F24LE,
    AV_CODEC_ID_PCM_VIDC,
    AV_CODEC_ID_PCM_SGA,
    AV_CODEC_ID_ADPCM_IMA_QT,
    AV_CODEC_ID_ADPCM_IMA_WAV,
    AV_CODEC_ID_ADPCM_IMA_DK3,
    AV_CODEC_ID_ADPCM_IMA_DK4,
    AV_CODEC_ID_ADPCM_IMA_WS,
    AV_CODEC_ID_ADPCM_IMA_SMJPEG,
    AV_CODEC_ID_ADPCM_MS,
    AV_CODEC_ID_ADPCM_4XM,
    AV_CODEC_ID_ADPCM_XA,
    AV_CODEC_ID_ADPCM_ADX,
    AV_CODEC_ID_ADPCM_EA,
    AV_CODEC_ID_ADPCM_G726,
    AV_CODEC_ID_ADPCM_CT,
    AV_CODEC_ID_ADPCM_SWF,
    AV_CODEC_ID_ADPCM_YAMAHA,
    AV_CODEC_ID_ADPCM_SBPRO_4,
    AV_CODEC_ID_ADPCM_SBPRO_3,
    AV_CODEC_ID_ADPCM_SBPRO_2,
    AV_CODEC_ID_ADPCM_THP,
    AV_CODEC_ID_ADPCM_IMA_AMV,
    AV_CODEC_ID_ADPCM_EA_R1,
    AV_CODEC_ID_ADPCM_EA_R3,
    AV_CODEC_ID_ADPCM_EA_R2,
    AV_CODEC_ID_ADPCM_IMA_EA_SEAD,
    AV_CODEC_ID_ADPCM_IMA_EA_EACS,
    AV_CODEC_ID_ADPCM_EA_XAS,
    AV_CODEC_ID_ADPCM_EA_MAXIS_XA,
    AV_CODEC_ID_ADPCM_IMA_ISS,
    AV_CODEC_ID_ADPCM_G722,
    AV_CODEC_ID_ADPCM_IMA_APC,
    AV_CODEC_ID_ADPCM_VIMA,
    AV_CODEC_ID_ADPCM_AFC,
    AV_CODEC_ID_ADPCM_IMA_OKI,
    AV_CODEC_ID_ADPCM_DTK,
    AV_CODEC_ID_ADPCM_IMA_RAD,
    AV_CODEC_ID_ADPCM_G726LE,
    AV_CODEC_ID_ADPCM_THP_LE,
    AV_CODEC_ID_ADPCM_PSX,
    AV_CODEC_ID_ADPCM_AICA,
    AV_CODEC_ID_ADPCM_IMA_DAT4,
    AV_CODEC_ID_ADPCM_MTAF,
    AV_CODEC_ID_ADPCM_AGM,
    AV_CODEC_ID_ADPCM_ARGO,
    AV_CODEC_ID_ADPCM_IMA_SSI,
    AV_CODEC_ID_ADPCM_ZORK,
    AV_CODEC_ID_ADPCM_IMA_APM,
    AV_CODEC_ID_ADPCM_IMA_ALP,
    AV_CODEC_ID_ADPCM_IMA_MTF,
    AV_CODEC_ID_ADPCM_IMA_CUNNING,
    AV_CODEC_ID_ADPCM_IMA_MOFLEX,
    AV_CODEC_ID_ADPCM_IMA_ACORN,
    AV_CODEC_ID_ADPCM_XMD,
    AV_CODEC_ID_AMR_NB,
    AV_CODEC_ID_AMR_WB,
    AV_CODEC_ID_RA_144,
    AV_CODEC_ID_RA_288,
    AV_CODEC_ID_ROQ_DPCM,
    AV_CODEC_ID_INTERPLAY_DPCM,
    AV_CODEC_ID_XAN_DPCM,
    AV_CODEC_ID_SOL_DPCM,
    AV_CODEC_ID_SDX2_DPCM,
    AV_CODEC_ID_GREMLIN_DPCM,
    AV_CODEC_ID_DERF_DPCM,
    AV_CODEC_ID_WADY_DPCM,
    AV_CODEC_ID_CBD2_DPCM,
};


enum AVCodecID codec_to_avcodec(codec_type c) {
    return codec_type_mapping[c];
}

codec_type avcodec_to_codec(enum AVCodecID id) {
    switch(id) {
        case AV_CODEC_ID_NONE: return CODEC_TYPE_UNKNOWN;
        case AV_CODEC_ID_AAC: return CODEC_TYPE_AAC;
        case AV_CODEC_ID_ALAC: return CODEC_TYPE_ALAC;
        case AV_CODEC_ID_FLAC: return CODEC_TYPE_FLAC;
        case AV_CODEC_ID_MP3: return CODEC_TYPE_MP3;
        case AV_CODEC_ID_OPUS: return CODEC_TYPE_OPUS;
        case AV_CODEC_ID_AC3: return CODEC_TYPE_AC3;
        case AV_CODEC_ID_EAC3: return CODEC_TYPE_EAC3;
        case AV_CODEC_ID_VORBIS: return CODEC_TYPE_VORBIS;
        case AV_CODEC_ID_MP2: return CODEC_TYPE_MP2;
        case AV_CODEC_ID_DTS: return CODEC_TYPE_DTS;
        case AV_CODEC_ID_DVAUDIO: return CODEC_TYPE_DVAUDIO;
        case AV_CODEC_ID_WMAV1: return CODEC_TYPE_WMAV1;
        case AV_CODEC_ID_WMAV2: return CODEC_TYPE_WMAV2;
        case AV_CODEC_ID_MACE3: return CODEC_TYPE_MACE3;
        case AV_CODEC_ID_MACE6: return CODEC_TYPE_MACE6;
        case AV_CODEC_ID_VMDAUDIO: return CODEC_TYPE_VMDAUDIO;
        case AV_CODEC_ID_MP3ADU: return CODEC_TYPE_MP3ADU;
        case AV_CODEC_ID_MP3ON4: return CODEC_TYPE_MP3ON4;
        case AV_CODEC_ID_SHORTEN: return CODEC_TYPE_SHORTEN;
        case AV_CODEC_ID_WESTWOOD_SND1: return CODEC_TYPE_WESTWOOD_SND1;
        case AV_CODEC_ID_GSM: return CODEC_TYPE_GSM;
        case AV_CODEC_ID_QDM2: return CODEC_TYPE_QDM2;
        case AV_CODEC_ID_COOK: return CODEC_TYPE_COOK;
        case AV_CODEC_ID_TRUESPEECH: return CODEC_TYPE_TRUESPEECH;
        case AV_CODEC_ID_TTA: return CODEC_TYPE_TTA;
        case AV_CODEC_ID_SMACKAUDIO: return CODEC_TYPE_SMACKAUDIO;
        case AV_CODEC_ID_QCELP: return CODEC_TYPE_QCELP;
        case AV_CODEC_ID_WAVPACK: return CODEC_TYPE_WAVPACK;
        case AV_CODEC_ID_DSICINAUDIO: return CODEC_TYPE_DSICINAUDIO;
        case AV_CODEC_ID_IMC: return CODEC_TYPE_IMC;
        case AV_CODEC_ID_MUSEPACK7: return CODEC_TYPE_MUSEPACK7;
        case AV_CODEC_ID_MLP: return CODEC_TYPE_MLP;
        case AV_CODEC_ID_GSM_MS: return CODEC_TYPE_GSM_MS;
        case AV_CODEC_ID_ATRAC3: return CODEC_TYPE_ATRAC3;
        case AV_CODEC_ID_APE: return CODEC_TYPE_APE;
        case AV_CODEC_ID_NELLYMOSER: return CODEC_TYPE_NELLYMOSER;
        case AV_CODEC_ID_MUSEPACK8: return CODEC_TYPE_MUSEPACK8;
        case AV_CODEC_ID_SPEEX: return CODEC_TYPE_SPEEX;
        case AV_CODEC_ID_WMAVOICE: return CODEC_TYPE_WMAVOICE;
        case AV_CODEC_ID_WMAPRO: return CODEC_TYPE_WMAPRO;
        case AV_CODEC_ID_WMALOSSLESS: return CODEC_TYPE_WMALOSSLESS;
        case AV_CODEC_ID_ATRAC3P: return CODEC_TYPE_ATRAC3P;
        case AV_CODEC_ID_SIPR: return CODEC_TYPE_SIPR;
        case AV_CODEC_ID_MP1: return CODEC_TYPE_MP1;
        case AV_CODEC_ID_TWINVQ: return CODEC_TYPE_TWINVQ;
        case AV_CODEC_ID_TRUEHD: return CODEC_TYPE_TRUEHD;
        case AV_CODEC_ID_MP4ALS: return CODEC_TYPE_MP4ALS;
        case AV_CODEC_ID_ATRAC1: return CODEC_TYPE_ATRAC1;
        case AV_CODEC_ID_BINKAUDIO_RDFT: return CODEC_TYPE_BINKAUDIO_RDFT;
        case AV_CODEC_ID_BINKAUDIO_DCT: return CODEC_TYPE_BINKAUDIO_DCT;
        case AV_CODEC_ID_AAC_LATM: return CODEC_TYPE_AAC_LATM;
        case AV_CODEC_ID_QDMC: return CODEC_TYPE_QDMC;
        case AV_CODEC_ID_CELT: return CODEC_TYPE_CELT;
        case AV_CODEC_ID_G723_1: return CODEC_TYPE_G723_1;
        case AV_CODEC_ID_G729: return CODEC_TYPE_G729;
        case AV_CODEC_ID_8SVX_EXP: return CODEC_TYPE_8SVX_EXP;
        case AV_CODEC_ID_8SVX_FIB: return CODEC_TYPE_8SVX_FIB;
        case AV_CODEC_ID_BMV_AUDIO: return CODEC_TYPE_BMV_AUDIO;
        case AV_CODEC_ID_RALF: return CODEC_TYPE_RALF;
        case AV_CODEC_ID_IAC: return CODEC_TYPE_IAC;
        case AV_CODEC_ID_ILBC: return CODEC_TYPE_ILBC;
        case AV_CODEC_ID_COMFORT_NOISE: return CODEC_TYPE_COMFORT_NOISE;
        case AV_CODEC_ID_TAK: return CODEC_TYPE_TAK;
        case AV_CODEC_ID_METASOUND: return CODEC_TYPE_METASOUND;
        case AV_CODEC_ID_PAF_AUDIO: return CODEC_TYPE_PAF_AUDIO;
        case AV_CODEC_ID_ON2AVC: return CODEC_TYPE_ON2AVC;
        case AV_CODEC_ID_DSS_SP: return CODEC_TYPE_DSS_SP;
        case AV_CODEC_ID_CODEC2: return CODEC_TYPE_CODEC2;
        case AV_CODEC_ID_FFWAVESYNTH: return CODEC_TYPE_FFWAVESYNTH;
        case AV_CODEC_ID_SONIC: return CODEC_TYPE_SONIC;
        case AV_CODEC_ID_SONIC_LS: return CODEC_TYPE_SONIC_LS;
        case AV_CODEC_ID_EVRC: return CODEC_TYPE_EVRC;
        case AV_CODEC_ID_SMV: return CODEC_TYPE_SMV;
        case AV_CODEC_ID_DSD_LSBF: return CODEC_TYPE_DSD_LSBF;
        case AV_CODEC_ID_DSD_MSBF: return CODEC_TYPE_DSD_MSBF;
        case AV_CODEC_ID_DSD_LSBF_PLANAR: return CODEC_TYPE_DSD_LSBF_PLANAR;
        case AV_CODEC_ID_DSD_MSBF_PLANAR: return CODEC_TYPE_DSD_MSBF_PLANAR;
        case AV_CODEC_ID_4GV: return CODEC_TYPE_4GV;
        case AV_CODEC_ID_INTERPLAY_ACM: return CODEC_TYPE_INTERPLAY_ACM;
        case AV_CODEC_ID_XMA1: return CODEC_TYPE_XMA1;
        case AV_CODEC_ID_XMA2: return CODEC_TYPE_XMA2;
        case AV_CODEC_ID_DST: return CODEC_TYPE_DST;
        case AV_CODEC_ID_ATRAC3AL: return CODEC_TYPE_ATRAC3AL;
        case AV_CODEC_ID_ATRAC3PAL: return CODEC_TYPE_ATRAC3PAL;
        case AV_CODEC_ID_DOLBY_E: return CODEC_TYPE_DOLBY_E;
        case AV_CODEC_ID_APTX: return CODEC_TYPE_APTX;
        case AV_CODEC_ID_APTX_HD: return CODEC_TYPE_APTX_HD;
        case AV_CODEC_ID_SBC: return CODEC_TYPE_SBC;
        case AV_CODEC_ID_ATRAC9: return CODEC_TYPE_ATRAC9;
        case AV_CODEC_ID_HCOM: return CODEC_TYPE_HCOM;
        case AV_CODEC_ID_ACELP_KELVIN: return CODEC_TYPE_ACELP_KELVIN;
        case AV_CODEC_ID_MPEGH_3D_AUDIO: return CODEC_TYPE_MPEGH_3D_AUDIO;
        case AV_CODEC_ID_SIREN: return CODEC_TYPE_SIREN;
        case AV_CODEC_ID_HCA: return CODEC_TYPE_HCA;
        case AV_CODEC_ID_FASTAUDIO: return CODEC_TYPE_FASTAUDIO;
        case AV_CODEC_ID_MSNSIREN: return CODEC_TYPE_MSNSIREN;
        case AV_CODEC_ID_DFPWM: return CODEC_TYPE_DFPWM;
        case AV_CODEC_ID_BONK: return CODEC_TYPE_BONK;
        case AV_CODEC_ID_MISC4: return CODEC_TYPE_MISC4;
        case AV_CODEC_ID_APAC: return CODEC_TYPE_APAC;
        case AV_CODEC_ID_FTR: return CODEC_TYPE_FTR;
        case AV_CODEC_ID_WAVARC: return CODEC_TYPE_WAVARC;
        case AV_CODEC_ID_RKA: return CODEC_TYPE_RKA;
        case AV_CODEC_ID_PCM_S16LE: return CODEC_TYPE_PCM_S16LE;
        case AV_CODEC_ID_PCM_S16BE: return CODEC_TYPE_PCM_S16BE;
        case AV_CODEC_ID_PCM_U16LE: return CODEC_TYPE_PCM_U16LE;
        case AV_CODEC_ID_PCM_U16BE: return CODEC_TYPE_PCM_U16BE;
        case AV_CODEC_ID_PCM_S8: return CODEC_TYPE_PCM_S8;
        case AV_CODEC_ID_PCM_U8: return CODEC_TYPE_PCM_U8;
        case AV_CODEC_ID_PCM_MULAW: return CODEC_TYPE_PCM_MULAW;
        case AV_CODEC_ID_PCM_ALAW: return CODEC_TYPE_PCM_ALAW;
        case AV_CODEC_ID_PCM_S32LE: return CODEC_TYPE_PCM_S32LE;
        case AV_CODEC_ID_PCM_S32BE: return CODEC_TYPE_PCM_S32BE;
        case AV_CODEC_ID_PCM_U32LE: return CODEC_TYPE_PCM_U32LE;
        case AV_CODEC_ID_PCM_U32BE: return CODEC_TYPE_PCM_U32BE;
        case AV_CODEC_ID_PCM_S24LE: return CODEC_TYPE_PCM_S24LE;
        case AV_CODEC_ID_PCM_S24BE: return CODEC_TYPE_PCM_S24BE;
        case AV_CODEC_ID_PCM_U24LE: return CODEC_TYPE_PCM_U24LE;
        case AV_CODEC_ID_PCM_U24BE: return CODEC_TYPE_PCM_U24BE;
        case AV_CODEC_ID_PCM_S24DAUD: return CODEC_TYPE_PCM_S24DAUD;
        case AV_CODEC_ID_PCM_ZORK: return CODEC_TYPE_PCM_ZORK;
        case AV_CODEC_ID_PCM_S16LE_PLANAR: return CODEC_TYPE_PCM_S16LE_PLANAR;
        case AV_CODEC_ID_PCM_DVD: return CODEC_TYPE_PCM_DVD;
        case AV_CODEC_ID_PCM_F32BE: return CODEC_TYPE_PCM_F32BE;
        case AV_CODEC_ID_PCM_F32LE: return CODEC_TYPE_PCM_F32LE;
        case AV_CODEC_ID_PCM_F64BE: return CODEC_TYPE_PCM_F64BE;
        case AV_CODEC_ID_PCM_F64LE: return CODEC_TYPE_PCM_F64LE;
        case AV_CODEC_ID_PCM_BLURAY: return CODEC_TYPE_PCM_BLURAY;
        case AV_CODEC_ID_PCM_LXF: return CODEC_TYPE_PCM_LXF;
        case AV_CODEC_ID_S302M: return CODEC_TYPE_S302M;
        case AV_CODEC_ID_PCM_S8_PLANAR: return CODEC_TYPE_PCM_S8_PLANAR;
        case AV_CODEC_ID_PCM_S24LE_PLANAR: return CODEC_TYPE_PCM_S24LE_PLANAR;
        case AV_CODEC_ID_PCM_S32LE_PLANAR: return CODEC_TYPE_PCM_S32LE_PLANAR;
        case AV_CODEC_ID_PCM_S16BE_PLANAR: return CODEC_TYPE_PCM_S16BE_PLANAR;
        case AV_CODEC_ID_PCM_S64LE: return CODEC_TYPE_PCM_S64LE;
        case AV_CODEC_ID_PCM_S64BE: return CODEC_TYPE_PCM_S64BE;
        case AV_CODEC_ID_PCM_F16LE: return CODEC_TYPE_PCM_F16LE;
        case AV_CODEC_ID_PCM_F24LE: return CODEC_TYPE_PCM_F24LE;
        case AV_CODEC_ID_PCM_VIDC: return CODEC_TYPE_PCM_VIDC;
        case AV_CODEC_ID_PCM_SGA: return CODEC_TYPE_PCM_SGA;
        case AV_CODEC_ID_ADPCM_IMA_QT: return CODEC_TYPE_ADPCM_IMA_QT;
        case AV_CODEC_ID_ADPCM_IMA_WAV: return CODEC_TYPE_ADPCM_IMA_WAV;
        case AV_CODEC_ID_ADPCM_IMA_DK3: return CODEC_TYPE_ADPCM_IMA_DK3;
        case AV_CODEC_ID_ADPCM_IMA_DK4: return CODEC_TYPE_ADPCM_IMA_DK4;
        case AV_CODEC_ID_ADPCM_IMA_WS: return CODEC_TYPE_ADPCM_IMA_WS;
        case AV_CODEC_ID_ADPCM_IMA_SMJPEG: return CODEC_TYPE_ADPCM_IMA_SMJPEG;
        case AV_CODEC_ID_ADPCM_MS: return CODEC_TYPE_ADPCM_MS;
        case AV_CODEC_ID_ADPCM_4XM: return CODEC_TYPE_ADPCM_4XM;
        case AV_CODEC_ID_ADPCM_XA: return CODEC_TYPE_ADPCM_XA;
        case AV_CODEC_ID_ADPCM_ADX: return CODEC_TYPE_ADPCM_ADX;
        case AV_CODEC_ID_ADPCM_EA: return CODEC_TYPE_ADPCM_EA;
        case AV_CODEC_ID_ADPCM_G726: return CODEC_TYPE_ADPCM_G726;
        case AV_CODEC_ID_ADPCM_CT: return CODEC_TYPE_ADPCM_CT;
        case AV_CODEC_ID_ADPCM_SWF: return CODEC_TYPE_ADPCM_SWF;
        case AV_CODEC_ID_ADPCM_YAMAHA: return CODEC_TYPE_ADPCM_YAMAHA;
        case AV_CODEC_ID_ADPCM_SBPRO_4: return CODEC_TYPE_ADPCM_SBPRO_4;
        case AV_CODEC_ID_ADPCM_SBPRO_3: return CODEC_TYPE_ADPCM_SBPRO_3;
        case AV_CODEC_ID_ADPCM_SBPRO_2: return CODEC_TYPE_ADPCM_SBPRO_2;
        case AV_CODEC_ID_ADPCM_THP: return CODEC_TYPE_ADPCM_THP;
        case AV_CODEC_ID_ADPCM_IMA_AMV: return CODEC_TYPE_ADPCM_IMA_AMV;
        case AV_CODEC_ID_ADPCM_EA_R1: return CODEC_TYPE_ADPCM_EA_R1;
        case AV_CODEC_ID_ADPCM_EA_R3: return CODEC_TYPE_ADPCM_EA_R3;
        case AV_CODEC_ID_ADPCM_EA_R2: return CODEC_TYPE_ADPCM_EA_R2;
        case AV_CODEC_ID_ADPCM_IMA_EA_SEAD: return CODEC_TYPE_ADPCM_IMA_EA_SEAD;
        case AV_CODEC_ID_ADPCM_IMA_EA_EACS: return CODEC_TYPE_ADPCM_IMA_EA_EACS;
        case AV_CODEC_ID_ADPCM_EA_XAS: return CODEC_TYPE_ADPCM_EA_XAS;
        case AV_CODEC_ID_ADPCM_EA_MAXIS_XA: return CODEC_TYPE_ADPCM_EA_MAXIS_XA;
        case AV_CODEC_ID_ADPCM_IMA_ISS: return CODEC_TYPE_ADPCM_IMA_ISS;
        case AV_CODEC_ID_ADPCM_G722: return CODEC_TYPE_ADPCM_G722;
        case AV_CODEC_ID_ADPCM_IMA_APC: return CODEC_TYPE_ADPCM_IMA_APC;
        case AV_CODEC_ID_ADPCM_VIMA: return CODEC_TYPE_ADPCM_VIMA;
        case AV_CODEC_ID_ADPCM_AFC: return CODEC_TYPE_ADPCM_AFC;
        case AV_CODEC_ID_ADPCM_IMA_OKI: return CODEC_TYPE_ADPCM_IMA_OKI;
        case AV_CODEC_ID_ADPCM_DTK: return CODEC_TYPE_ADPCM_DTK;
        case AV_CODEC_ID_ADPCM_IMA_RAD: return CODEC_TYPE_ADPCM_IMA_RAD;
        case AV_CODEC_ID_ADPCM_G726LE: return CODEC_TYPE_ADPCM_G726LE;
        case AV_CODEC_ID_ADPCM_THP_LE: return CODEC_TYPE_ADPCM_THP_LE;
        case AV_CODEC_ID_ADPCM_PSX: return CODEC_TYPE_ADPCM_PSX;
        case AV_CODEC_ID_ADPCM_AICA: return CODEC_TYPE_ADPCM_AICA;
        case AV_CODEC_ID_ADPCM_IMA_DAT4: return CODEC_TYPE_ADPCM_IMA_DAT4;
        case AV_CODEC_ID_ADPCM_MTAF: return CODEC_TYPE_ADPCM_MTAF;
        case AV_CODEC_ID_ADPCM_AGM: return CODEC_TYPE_ADPCM_AGM;
        case AV_CODEC_ID_ADPCM_ARGO: return CODEC_TYPE_ADPCM_ARGO;
        case AV_CODEC_ID_ADPCM_IMA_SSI: return CODEC_TYPE_ADPCM_IMA_SSI;
        case AV_CODEC_ID_ADPCM_ZORK: return CODEC_TYPE_ADPCM_ZORK;
        case AV_CODEC_ID_ADPCM_IMA_APM: return CODEC_TYPE_ADPCM_IMA_APM;
        case AV_CODEC_ID_ADPCM_IMA_ALP: return CODEC_TYPE_ADPCM_IMA_ALP;
        case AV_CODEC_ID_ADPCM_IMA_MTF: return CODEC_TYPE_ADPCM_IMA_MTF;
        case AV_CODEC_ID_ADPCM_IMA_CUNNING: return CODEC_TYPE_ADPCM_IMA_CUNNING;
        case AV_CODEC_ID_ADPCM_IMA_MOFLEX: return CODEC_TYPE_ADPCM_IMA_MOFLEX;
        case AV_CODEC_ID_ADPCM_IMA_ACORN: return CODEC_TYPE_ADPCM_IMA_ACORN;
        case AV_CODEC_ID_ADPCM_XMD: return CODEC_TYPE_ADPCM_XMD;
        case AV_CODEC_ID_AMR_NB: return CODEC_TYPE_AMR_NB;
        case AV_CODEC_ID_AMR_WB: return CODEC_TYPE_AMR_WB;
        case AV_CODEC_ID_RA_144: return CODEC_TYPE_RA_144;
        case AV_CODEC_ID_RA_288: return CODEC_TYPE_RA_288;
        case AV_CODEC_ID_ROQ_DPCM: return CODEC_TYPE_ROQ_DPCM;
        case AV_CODEC_ID_INTERPLAY_DPCM: return CODEC_TYPE_INTERPLAY_DPCM;
        case AV_CODEC_ID_XAN_DPCM: return CODEC_TYPE_XAN_DPCM;
        case AV_CODEC_ID_SOL_DPCM: return CODEC_TYPE_SOL_DPCM;
        case AV_CODEC_ID_SDX2_DPCM: return CODEC_TYPE_SDX2_DPCM;
        case AV_CODEC_ID_GREMLIN_DPCM: return CODEC_TYPE_GREMLIN_DPCM;
        case AV_CODEC_ID_DERF_DPCM: return CODEC_TYPE_DERF_DPCM;
        case AV_CODEC_ID_WADY_DPCM: return CODEC_TYPE_WADY_DPCM;
        case AV_CODEC_ID_CBD2_DPCM: return CODEC_TYPE_CBD2_DPCM;
        default: break;
    }
    return CODEC_TYPE_UNKNOWN;
}
